# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: broker.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'broker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62roker.proto\"\x1f\n\nClientInfo\x12\x11\n\tclient_id\x18\x01 \x01(\t\"\x16\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\'\n\x12SongRequestMessage\x12\x11\n\tsong_name\x18\x01 \x01(\t\"0\n\x0cSongResponse\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"2\n\nSongUpdate\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x11\n\tsong_name\x18\x02 \x01(\t\"6\n\x12SongUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x94\x02\n\x0eNapsterService\x12\x1e\n\tHeartbeat\x12\x0b.ClientInfo\x1a\x04.Ack\x12\x36\n\x10InitializeClient\x12\x0b.SongUpdate\x1a\x13.SongUpdateResponse(\x01\x12\x1a\n\x05Leave\x12\x0b.ClientInfo\x1a\x04.Ack\x12\x31\n\x0bSongRequest\x12\x13.SongRequestMessage\x1a\r.SongResponse\x12+\n\x07\x41\x64\x64Song\x12\x0b.SongUpdate\x1a\x13.SongUpdateResponse\x12.\n\nDeleteSong\x12\x0b.SongUpdate\x1a\x13.SongUpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'broker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTINFO']._serialized_start=16
  _globals['_CLIENTINFO']._serialized_end=47
  _globals['_ACK']._serialized_start=49
  _globals['_ACK']._serialized_end=71
  _globals['_SONGREQUESTMESSAGE']._serialized_start=73
  _globals['_SONGREQUESTMESSAGE']._serialized_end=112
  _globals['_SONGRESPONSE']._serialized_start=114
  _globals['_SONGRESPONSE']._serialized_end=162
  _globals['_SONGUPDATE']._serialized_start=164
  _globals['_SONGUPDATE']._serialized_end=214
  _globals['_SONGUPDATERESPONSE']._serialized_start=216
  _globals['_SONGUPDATERESPONSE']._serialized_end=270
  _globals['_NAPSTERSERVICE']._serialized_start=273
  _globals['_NAPSTERSERVICE']._serialized_end=549
# @@protoc_insertion_point(module_scope)
