# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import broker_pb2 as broker__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in broker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NapsterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/NapsterService/Heartbeat',
                request_serializer=broker__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=broker__pb2.Ack.FromString,
                _registered_method=True)
        self.InitializeClient = channel.stream_stream(
                '/NapsterService/InitializeClient',
                request_serializer=broker__pb2.SongUpdate.SerializeToString,
                response_deserializer=broker__pb2.Update.FromString,
                _registered_method=True)
        self.Leave = channel.unary_unary(
                '/NapsterService/Leave',
                request_serializer=broker__pb2.ClientInfo.SerializeToString,
                response_deserializer=broker__pb2.Ack.FromString,
                _registered_method=True)
        self.SongRequest = channel.unary_unary(
                '/NapsterService/SongRequest',
                request_serializer=broker__pb2.SongRequestMessage.SerializeToString,
                response_deserializer=broker__pb2.SongResponse.FromString,
                _registered_method=True)
        self.AddSong = channel.unary_unary(
                '/NapsterService/AddSong',
                request_serializer=broker__pb2.SongUpdate.SerializeToString,
                response_deserializer=broker__pb2.SongUpdateResponse.FromString,
                _registered_method=True)
        self.DeleteSong = channel.unary_unary(
                '/NapsterService/DeleteSong',
                request_serializer=broker__pb2.SongUpdate.SerializeToString,
                response_deserializer=broker__pb2.SongUpdateResponse.FromString,
                _registered_method=True)
        self.PullUpdates = channel.unary_stream(
                '/NapsterService/PullUpdates',
                request_serializer=broker__pb2.ClientInfo.SerializeToString,
                response_deserializer=broker__pb2.Update.FromString,
                _registered_method=True)
        self.Report = channel.unary_unary(
                '/NapsterService/Report',
                request_serializer=broker__pb2.ClientInfo.SerializeToString,
                response_deserializer=broker__pb2.Ack.FromString,
                _registered_method=True)


class NapsterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitializeClient(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Leave(self, request, context):
        """graceful leave
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SongRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Report(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NapsterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=broker__pb2.HeartbeatRequest.FromString,
                    response_serializer=broker__pb2.Ack.SerializeToString,
            ),
            'InitializeClient': grpc.stream_stream_rpc_method_handler(
                    servicer.InitializeClient,
                    request_deserializer=broker__pb2.SongUpdate.FromString,
                    response_serializer=broker__pb2.Update.SerializeToString,
            ),
            'Leave': grpc.unary_unary_rpc_method_handler(
                    servicer.Leave,
                    request_deserializer=broker__pb2.ClientInfo.FromString,
                    response_serializer=broker__pb2.Ack.SerializeToString,
            ),
            'SongRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.SongRequest,
                    request_deserializer=broker__pb2.SongRequestMessage.FromString,
                    response_serializer=broker__pb2.SongResponse.SerializeToString,
            ),
            'AddSong': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSong,
                    request_deserializer=broker__pb2.SongUpdate.FromString,
                    response_serializer=broker__pb2.SongUpdateResponse.SerializeToString,
            ),
            'DeleteSong': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSong,
                    request_deserializer=broker__pb2.SongUpdate.FromString,
                    response_serializer=broker__pb2.SongUpdateResponse.SerializeToString,
            ),
            'PullUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.PullUpdates,
                    request_deserializer=broker__pb2.ClientInfo.FromString,
                    response_serializer=broker__pb2.Update.SerializeToString,
            ),
            'Report': grpc.unary_unary_rpc_method_handler(
                    servicer.Report,
                    request_deserializer=broker__pb2.ClientInfo.FromString,
                    response_serializer=broker__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NapsterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('NapsterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NapsterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NapsterService/Heartbeat',
            broker__pb2.HeartbeatRequest.SerializeToString,
            broker__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitializeClient(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/NapsterService/InitializeClient',
            broker__pb2.SongUpdate.SerializeToString,
            broker__pb2.Update.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Leave(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NapsterService/Leave',
            broker__pb2.ClientInfo.SerializeToString,
            broker__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SongRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NapsterService/SongRequest',
            broker__pb2.SongRequestMessage.SerializeToString,
            broker__pb2.SongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NapsterService/AddSong',
            broker__pb2.SongUpdate.SerializeToString,
            broker__pb2.SongUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NapsterService/DeleteSong',
            broker__pb2.SongUpdate.SerializeToString,
            broker__pb2.SongUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/NapsterService/PullUpdates',
            broker__pb2.ClientInfo.SerializeToString,
            broker__pb2.Update.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Report(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NapsterService/Report',
            broker__pb2.ClientInfo.SerializeToString,
            broker__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
